app:
  name: api-golang-template
  kv_name: kvname-dev
  env: local
  port: 9000

server:
  pretty_print: true
  log_level: debug # debug, info, warn, error
  idle_timeout: 1m
  read_timeout: 1m
  write_timeout: 1m

service:
  debug: true
  vault_url: http://localhost:8200
